title: AI-in-UAE News
theme: minima

collections:
  news:
    output: true
    permalink: /news/:slug/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2  # Note: use jekyll-paginate-v2 for collection pagination

pagination:
  enabled: true
  per_page: 50
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_reverse: true
